"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from 'react-redux';
import { store } from "@/store";
import { ThemeProvider } from "next-themes";
import { Poppins } from "next/font/google";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const poppins = Poppins({ weight: ["400"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ThemeProvider attribute="class" defaultTheme="dark">
        <Provider store={store}>
            <html lang="en">
              <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased ${poppins.className}`}
              >
                {children}
              </body>
            </html>
        </Provider>
      </ThemeProvider>
  );
}
